CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS audit.organizacoes (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(120) NOT NULL,
ativo BOOLEAN NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT organizacoes_nome_key UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS audit.usuarios (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
organizacao_id BIGINT NOT NULL,
nome VARCHAR(120) NOT NULL,
email VARCHAR(180) NOT NULL,
senha_hash VARCHAR(255) NOT NULL,
status VARCHAR(30) NOT NULL,
ultimo_login_em TIMESTAMP WITH TIME ZONE,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_usuarios_org FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
CONSTRAINT uq_usuarios_email_por_org UNIQUE (email, organizacao_id)
);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON audit.usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_org ON audit.usuarios(organizacao_id);

CREATE TABLE IF NOT EXISTS audit.permissions (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
code VARCHAR(80) NOT NULL,
descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit.roles (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
organizacao_id BIGINT NOT NULL,
nome VARCHAR(60) NOT NULL,
descricao VARCHAR(255),
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_roles_org FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
CONSTRAINT uq_roles_nome_por_org UNIQUE (organizacao_id, nome)
);

CREATE TABLE IF NOT EXISTS audit.role_permissions (
role_id BIGINT NOT NULL,
permission_id BIGINT NOT NULL,
PRIMARY KEY (role_id, permission_id),
CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES audit.roles(id),
CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES audit.permissions(id)
);

CREATE TABLE IF NOT EXISTS audit.user_roles (
usuario_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
granted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (usuario_id, role_id),
CONSTRAINT fk_ur_user FOREIGN KEY (usuario_id) REFERENCES audit.usuarios(id),
CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES audit.roles(id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON audit.user_roles(usuario_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON audit.user_roles(role_id);

CREATE TABLE IF NOT EXISTS audit.api_keys (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
organizacao_id BIGINT NOT NULL,
nome VARCHAR(120) NOT NULL,
key_hash VARCHAR(255) NOT NULL,
ativo BOOLEAN NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
last_used_at TIMESTAMP WITH TIME ZONE,
CONSTRAINT fk_api_keys_org FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
CONSTRAINT uq_api_keys_nome_por_org UNIQUE (organizacao_id, nome),
CONSTRAINT uq_api_keys_key_hash UNIQUE (key_hash)
);

CREATE TABLE IF NOT EXISTS audit.audit_entries (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
organizacao_id BIGINT NOT NULL,
actor_user_id BIGINT,
actor_api_key_id BIGINT,
action VARCHAR(30) NOT NULL,
entity_schema VARCHAR(60) NOT NULL,
entity_name VARCHAR(60) NOT NULL,
entity_id VARCHAR(80),
occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
ip VARCHAR(255),
user_agent VARCHAR(255),
diff VARCHAR(1000000000),
metadata VARCHAR(1000000000),
success BOOLEAN NOT NULL,
CONSTRAINT fk_audit_org FOREIGN KEY (organizacao_id) REFERENCES audit.organizacoes(id),
CONSTRAINT fk_audit_actor_user FOREIGN KEY (actor_user_id) REFERENCES audit.usuarios(id),
CONSTRAINT fk_audit_actor_api_key FOREIGN KEY (actor_api_key_id) REFERENCES audit.api_keys(id),
CONSTRAINT chk_audit_auction CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT','EXPORT', 'IMPORT','ERROR'))
);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit.audit_entries(action);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit.audit_entries(entity_schema, entity_name, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_org_time ON audit.audit_entries(organizacao_id, occurred_at);
